app_user:
    resource: ../../src/Config/routes/user.yml
    prefix: /

app_publication:
    resource: ../../src/Config/routes/publications.yml
    prefix: /

app_following:
    resource: ../../src/Config/routes/following.yml
    prefix: /