app_homepage:
    path: /home
    defaults: { _controller: App\Controller\PublicationController:index }

remove_publication:
    path: /publication/remove/{id}
    defaults: { _controller: App\Controller\PublicationController:removePublication, id: null }
    methods: [GET]