login:
    path: /login
    defaults: { _controller: App\Controller\UserController:login }

login_check:
    path: /login_check

logout:
    path: /logout

register:
    path: /register
    defaults: { _controller: App\Controller\UserController:register }

user_nick_test:
    path: /nick-test
    defaults: { _controller: App\Controller\UserController:nickTest }
    methods: [POST]

edit_user:
    path: /my-data
    defaults: { _controller: App\Controller\UserController:editUser }

user_list:
    path: /people
    defaults: { _controller: App\Controller\UserController:users }

user_search:
    path: /search
    defaults: { _controller: App\Controller\UserController:search }